Traceback (most recent call last):
  File "C:\Users\ual-laptop\Desktop\Visalakshi\College\APPLIED NLP INFO 555\Project 4\simscripts\simulation_928.py", line 58, in <module>
    main()
  File "C:\Users\ual-laptop\Desktop\Visalakshi\College\APPLIED NLP INFO 555\Project 4\simscripts\simulation_928.py", line 54, in main
    simulation = Simulation()
                 ^^^^^^^^^^^^
  File "C:\Users\ual-laptop\Desktop\Visalakshi\College\APPLIED NLP INFO 555\Project 4\simscripts\simulation_928.py", line 40, in __init__
    self.rootObject = self._initialize_simulation()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ual-laptop\Desktop\Visalakshi\College\APPLIED NLP INFO 555\Project 4\simscripts\simulation_928.py", line 45, in _initialize_simulation
    patient1 = Patient("Patient A", True, 6.0, True)  # has alpha thalassemia
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ual-laptop\Desktop\Visalakshi\College\APPLIED NLP INFO 555\Project 4\simscripts\simulation_928.py", line 13, in __init__
    "vulnerability_to_SMA": self.calculate_vulnerability()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ual-laptop\Desktop\Visalakshi\College\APPLIED NLP INFO 555\Project 4\simscripts\simulation_928.py", line 18, in calculate_vulnerability
    if self.properties["has_alpha_thalassemia"]:
       ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'has_alpha_thalassemia'
